name: Apply

on:
  pull_request:
    types:
      - closed

concurrency: apply_terraform

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  apply:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: aws
    steps:
      - uses: actions/checkout@v3

      - name: Download Terraform Plan
        uses: dawidd6/action-download-artifact@v2
        with:
          name: plan
          workflow: plan.yml
          workflow_conclusion: success
          commit: ${{ github.event.pull_request.head.sha }}
          path: ./aws-configuration

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.4

      - name: Initialise Terraform
        working-directory: ./aws-configuration
        run: terraform init

      - name: Apply Terraform
        working-directory: ./aws-configuration
        run: terraform apply ./terraform.plan