name: import

on:
  workflow_dispatch:
    inputs:
      import-to:
        description: 'The terraform resource to import to.'     
        required: true
      import-from:
        description: 'The aws resource to import from.'     
        required: true

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.4

      - name: Initialise Terraform
        working-directory: ./aws-configuration
        run: terraform init

      - name: Import Terraform
        working-directory: ./aws-configuration
        run: terraform import ${{ github.event.inputs.import-to }} ${{ github.event.inputs.import-from }}